providers:
  - name: Local
    type: local

tests:
  - name: Chrome - Chrome
    browsers:
      - name: Chrome 1
        type: chrome
        provider: Local
      - name: Chrome 2
        type: chrome
        provider: Local

  - name: Chrome - Firefox
    browsers:
      - name: Chrome
        type: chrome
        provider: Local
      - name: Firefox
        type: firefox
        provider: Local

  - name: Firefox - Firefox
    browsers:
      - name: Firefox 1
        type: firefox
        provider: Local
      - name: Firefox 2
        type: firefox
        provider: Local
