providers:
  - name: Local
    type: local

instances:
  - name: Jitsi Meet
    type: jitsi
    url: https://meet.jit.si/
    room:
      name: jitsi-tests-room

tests:
  - name: Chrome - Chrome
    instance: Jitsi Meet
    browsers:
      - name: Chrome 1
        type: chrome
        provider: Local
      - name: Chrome 2
        type: chrome
        provider: Local

  - name: Chrome - Firefox
    instance: Jitsi Meet
    browsers:
      - name: Chrome
        type: chrome
        provider: Local
      - name: Firefox
        type: firefox
        provider: Local

  - name: Firefox - Firefox
    instance: Jitsi Meet
    browsers:
      - name: Firefox 1
        type: firefox
        provider: Local
      - name: Firefox 2
        type: firefox
        provider: Local
