providers:
  - name: Local
    type: local

instances:
  - name: Jitsi Meet
    type: jitsi
    url: https://meet.jit.si/
    room:
      name: jitsi-tests-room
      randomSuffix: true

scenarios:
  - name: Jitsi Meet Base
    tasks:
      # start a Jitsi Meet call (fill display name if required)
      - jitsi/call/start:
          # timeout for waiting all other browsers
          timeout: 60000

          # check for a prejoin page, but not required to have one
          prejoin: true
          prejoinRequired: false

          # check for a display name prompt, but not required to have one
          prompt: true
          promptRequired: false

      # some checks on videos
      - jitsi/video/number:
          exact: false

      # wait that all browsers finished to do some checks on videos
      - synchro:
          name: wait-videos
          timeout: 5000 # 5 seconds

      - jitsi/stats

      # wait that all browsers finished to do some checks on webrtc stats
      - synchro:
          name: wait-stats
          timeout: 5000 # 5 seconds

      # click on the hangup button
      - jitsi/call/end

tests:
  - name: Chrome - Chrome
    instance: Jitsi Meet
    scenario: Jitsi Meet Base
    browsers:
      - name: Chrome 1
        type: chrome
        provider: Local
      - name: Chrome 2
        type: chrome
        provider: Local

  - name: Chrome - Firefox
    instance: Jitsi Meet
    scenario: Jitsi Meet Base
    browsers:
      - name: Chrome
        type: chrome
        provider: Local
      - name: Firefox
        type: firefox
        provider: Local

  - name: Firefox - Firefox
    instance: Jitsi Meet
    scenario: Jitsi Meet Base
    browsers:
      - name: Firefox 1
        type: firefox
        provider: Local
      - name: Firefox 2
        type: firefox
        provider: Local
